read1:
	clear
	gcc a1.c -o read_dataset1.bin -O3 -fPIC -Wall -pedantic -D DATASET1

debug1:
	clear
	gcc a1.c -o read_debug_dataset1.bin -O3 -fPIC -Wall -pedantic -D DATASET1 -D DEBUG

read2:
	clear
	gcc a1.c -o read_dataset1.bin -O3 -fPIC -Wall -pedantic -D DATASET2

debug2:
	clear
	gcc a1.c -o read_debug_dataset1.bin -O3 -fPIC -Wall -pedantic -D DATASET2 -D DEBUG


csqsum:
	clear
	gcc a1.c -o csqsum.bin -O3 -fPIC -Wall -pedantic -D DATASET1 -D CSQSUM

csqsum_debug:
	clear
	gcc a1.c -o csqsum_debug.bin -O3 -fPIC -Wall -pedantic -D DATASET1 -D CSQSUM -D DEBUG
