read:
	clear
	gcc a1.c -o read_dataset1.bin -O3 -fPIC -Wall -pedantic

debug:
	clear
	gcc a1.c -o read_debug_dataset1.bin -O3 -fPIC -Wall -pedantic -D DEBUG

csqsum:
	clear
	gcc a1.c -o csqsum.bin -O3 -fPIC -Wall -pedantic -D CSQSUM

csqsum_debug:
	clear
	gcc a1.c -o csqsum_debug.bin -O3 -fPIC -Wall -pedantic -D CSQSUM -D DEBUG
